### ISSUE TITLE
Add configuration file support

### ISSUE THREAD

**Issue by willtech3** [willtech3/claude-agent#5]
## Description
Support configuration files for default settings and repo-specific preferences.

## Tasks
- [ ] Support ~/.claude-agent/config.yml for user defaults
- [ ] Support .claude-agent.yml in repositories for project settings
- [ ] Allow overriding: default max-turns, excluded files, branch naming
- [ ] Environment variable support for all settings
- [ ] Config file validation and error handling

## Example Config File
```yaml
# ~/.claude-agent/config.yml
defaults:
  max_turns: 15
  output_format: json
  
github:
  token_command: "op read op://Personal/GitHub/token"  # 1Password integration
  default_labels: ["claude-agent", "automated"]
  
exclude_patterns:
  - "*.min.js"
  - "dist/**"
  - "vendor/**"

branch_naming:
  prefix: "auto"  # auto/issue-123 instead of claude/issue-123
```

## Priority
Medium - Improves usability for power users
