### ISSUE TITLE
Add safety features and confirmations

### ISSUE THREAD

**Issue by willtech3** [willtech3/claude-agent#9]
## Description
Add safety nets to prevent unintended changes.

## Tasks
- [ ] Add `--confirm` flag to review changes before PR creation
- [ ] Support exclude patterns for protected files
- [ ] Warn about modifications to critical files
- [ ] Add `--force` flag to bypass safety checks
- [ ] Detect and warn about branch protection rules

## Safety Features
```yaml
# Default protected patterns
protected_files:
  - .github/workflows/**
  - **/secrets.*
  - .env*
  
# Warning for large changes
warn_thresholds:
  files_changed: 20
  lines_changed: 500
```

## Example Flow
```
🤖 Claude Agent completed task

⚠️  Large change detected:
- 15 files modified
- 350 lines added, 200 removed

Review changes? [Y/n]: y
[Shows diff summary]

Create PR? [Y/n]: y
```

## Priority
Low - Additional safety for cautious users
